//https://dashboard.blooket.com/blooks
(()=>{
    const blooksList = [
    "Alice",
    "Alien",
    "Amber",
    "Angry Bot",
    "Blobfish",
    "Brainy Bot",
    "Brontosaurus",
    "Buddy Bot",
    "Bush Monster",
    "Cereal",
    "Cheshire Cat",
    "Clownfish",
    "Crab",
    "Dink",
    "Dino Egg",
    "Dino Fossil",
    "Donk",
    "Dormouse",
    "Drink Me",
    "Earth",
    "Eat Me",
    "Elephant",
    "Fairy",
    "Flamingo",
    "Frankenstein",
    "French Toast",
    "Frog",
    "Happy Bot",
    "Holiday Wreath",
    "Ice Bat",
    "Ice Bug",
    "Ice Elemental",
    "Ice Slime",
    "Jellyfish",
    "King",
    "Lemur",
    "Lil Bot",
    "Lovely Bot",
    "Mad Hatter",
    "Meteor",
    "Milk",
    "Mummy",
    "Narwhal",
    "Octopus",
    "Old Boot",
    "Orange Juice",
    "Pancakes",
    "Panda",
    "Peacock",
    "Planet",
    "Pufferfish",
    "Pumpkin",
    "Queen",
    "Queen of Hearts",
    "Rock Monster",
    "Slime Monster",
    "Sloth",
    "Snowman",
    "Spaceship",
    "Stars",
    "Stegosaurus",
    "Swamp Monster",
    "Tenrec",
    "Toast",
    "Two of Spades",
    "UFO",
    "Unicorn",
    "Vampire",
    "Velociraptor",
    "Watson",
    "White Rabbit",
    "Witch",
    "Yogurt",
    "Zebra",
    "Zombie",
    "Frost Wreath",
    "Gingerbread House",
    "Gingerbread Man",
    "Holiday Gift",
    "Hot Chocolate",
    "Santa Claus",
    "Snow Globe",
    "Tropical Globe",
    "Mega Bot",
    "Breakfast Combo",
    "Pizza",
    "Waffle",
    "Wizard",
    "Jester",
    "Elf",
    "Dragon",
    "Astronaut",
    "Black Atronaut",
    "Yellow Atronaut",
    "Ghost",
    "Werewolf",
    "Spooky Ghost",
    "Spooky Mummy",
    "Spooky Pumpkin",
    "King of Hearts",
    "Sandwich",
    "Baby Shark",
    "Megalodon",
    "Lovely Frog",
    "Chameleon",
    "Lion",
    "Rainbow Panda",
    "White Peacock",
    "Tiger Zebra",
    "Yeti",
    "Frozen Fossil",
    "Ice Crab",
    "Triceratops",
    "Tyrannosaurus Rex",
    "Tim the Alien",
    "Phantom King",
    "Rainbow Astronaut",
    "Lime Astronaut",
    "Cyan Astronaut",
    "Agent Owl",
    "Master Elf",
    "Purple Astronaut",
    "Blue Astronaut",
    "Caterpillar",
    "Red Astronaut",
    "Orange Astronaut",
    "Yellow Astronaut",
    "Green Astronaut",
    "Black Astronaut",
    "Pink Astronaut",
    "Brown Astronaut"
];
    const dict = {}
    for(let i of Object.values(blooksList)){
        dict[i]=1;
    }
    getStateNode().setState({blookData: dict})
})();
